### ISSUE TITLE
How to login with cookie?

### ISSUE THREAD

**Issue by jet10000** [frankie567/fastapi-users#111]
Hi, I create a login form page , I want to login it with cookie, How to do it? I test it , but not work.

```
auth_backends = [
    CookieAuthentication(secret=SECRET, lifetime_seconds=3600),
    # JWTAuthentication(secret=SECRET, lifetime_seconds=3600),
]

fastapi_users = FastAPIUsers(
    user_db, auth_backends, User, UserCreate, UserUpdate, UserDB, SECRET,
)
app.include_router(fastapi_users.router, prefix="/users", tags=["users"])

templates = Jinja2Templates(directory='templates')
...

@app.get("/")
async def read_root(user: User = Depends(fastapi_users.get_current_active_user)):
    return {"Hello": f"{user.email}"}


@app.route("/login", methods=['GET'])
async def login(request):
    return templates.TemplateResponse('login.html', {'request': request})
```
template
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<form method="post" action="/users/login/cookie">
    <input name="username" autocomplete="off">
    <input name="password" autocomplete="off">
    <button>submit</button>
</form>
</body>
</html>
```

I access Login page and input username and password, then submit it, response null, then I access homepage "http://127.0.0.1:8000", but still display `{"detail":"Unauthorized"}`

**Comment by frankie567** [comment]
Hi @jet10000! FastAPI is more intended to be used as a REST API framework rather than a traditional website you could do in Django.

That said, we should be able to make what you’ve done working. First of all, since you are in local, you should configure `cookie_secure` to `False` (it’s HTTPS only by default) : https://frankie567.github.io/fastapi-users/configuration/authentication/cookie/

You should watch the response of your request in the Network tab of your browser, that will get you useful information (like status code and the cookie output).

Once you made it work, I would recommend to write a bit of JavaScript in your page to handle the form submission, handle the response and make the redirection. Again, the purpose of FastAPI is to be used as an API.

Cheers!

**Comment by jet10000** [comment]
It's worked!  👍 

Thank you!
