### ISSUE TITLE
help about signin and logout

### ISSUE THREAD

**Issue by BenjPy** [frankie567/fastapi-users#154]
i don't see on below the Authenticated and Superuser in the swagger(openAPI)
based on the example doc
```
Authenticated
GET /me
PATCH /me
Superuser
GET /
GET /{user_id}
PATCH /{user_id}
DELETE /{user_id}
```
![image](https://user-images.githubusercontent.com/52538873/79555637-94f27480-80a8-11ea-9143-67d61ecd86e4.png)

btw: that will be nice to have doc that explain the flow method authentication
question 2: 
 the logout of the JWT Authentication are not implemented
my question: it's bug  or should inheriting from the class `JWTAuthentication` and i need  to implement  the method,
and  also in the class `SQLAlchemyBaseUserTable` i should to implement and put user as inactive?

thanks in advance

**Comment by frankie567** [comment]
Hi @BenjPy!

Thank you for reaching out! I'll try to answer point by point:

1. Superuser routes *are* there in the Swagger API, we see them on your screenshot. What I meant in the doc is that only superusers (i.e. users with `is_superuser == True`) can call those endpoints. If you call them while not being a superuser, you'll get a 403 error. Maybe this needs some clarifications in the doc.

2. JWT logout method is not implemented on purpose, because logging out with a JWT makes no sense (a JWT is valid until it expires, you can't revoke it server-side). If you have a look at the Cookie authentication, you'll see it's implemented.

3. I'm not sure to understand. If you wish to put `is_active` to `False` by default, maybe you could override it like this:

```py
from sqlalchemy import Boolean, Column

class UserTable(Base, SQLAlchemyBaseUserTable):
    is_active = Column(Boolean, default=False, nullable=False)
```

Cheers!

**Comment by BenjPy** [comment]
Hi Frank
 thank you for the the fast response
yep that will be nice if the doc can be more clarified
explain step by step  the flow of the admin admin user
and will be nice to see the curl cmd is more readable 


i'm trying to register a user as superuser and got response  when that insert in the db hat put false

```
curl -X POST "http://127.0.0.1:8000/users/register" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"id\":\"string\",\"email\":\"admin@admin.com\",\"is_active\":true,\"is_superuser\":true,\"password\":\"admin\"}"
```
the response
```
{"id":"d4991f38-f14a-4460-ba9f-5fe6b15c8e8e","email":"admin@admin.com","is_active":true,"is_superuser":false}
```
log
```
Query: INSERT INTO user (id, email, hashed_password, is_active, is_superuser) VALUES (?, ?, ?, ?, ?) Args: ('d4991f38-f14a-4460-ba9f-5fe6b15c8e8e', 'admin@admin.com', '$2b$12$4AnzvGeKpx/fa6n9yAgT5OaZUAxcuBnudhlbaaeX2mjIep39E2sBu', 1, 0)


```
maybe i'm doing something wrong
can you help , or clarify what i'm doing wrong
btw after updating in the db `is_superuser` to 1 that work
```
curl -X GET "http://127.0.0.1:8000/users/" -H "accept: application/json" -H "Authorization: Bearer $token"
```
output
```
[{"id":"d8146e2a-2fd8-4f87-8461-8fb11114e550","email":"test@test.com","is_active":true,"is_superuser":false},{"id":"d4991f38-f14a-4460-ba9f-5fe6b15c8e8e","email":"admin@admin.com","is_active":true,"is_superuser":true}]
```


thank in advance

**Comment by frankie567** [comment]
Hi @BenjPy!

This is expected behavior. A random person cannot register themself as a superuser (otherwise, a malicious guy could come and destroy everything!).

If you look at the [`/register` route doc](https://frankie567.github.io/fastapi-users/usage/routes/#post-register), you'll see that only `email` and `password` are needed. `is_active` and `is_superuser` will be ignored.

However, you can make a user a superuser by:
* Changing it manually in the database (as you did!)
* If you are logged in as an existing superuser, you can `PATCH` another user to change the flag:

```sh
curl -X PATCH "http://localhost:8000/users/UserIdToPromote" -H "Authorization: Bearer SuperUserToken" -d "{\"is_superuser\": true}"
```

I'll clarify the docs about all the points you raised :)

**Comment by BenjPy** [comment]
thank you for the answer 
yep the doc need more clarification because you  develop an API, that should used   by user
and if needed can be extended by some extra code.
Fastapi is framework  for building API so the doc refer how to implement api 
but  you have build API that can be extended with extra code
so the doc should appear with more example and flow and how to use it

**Comment by frankie567** [comment]
I've added a complete flow example here : https://frankie567.github.io/fastapi-users/usage/flow/

Hope it will help 👍

**Comment by BenjPy** [comment]
thank you very much @frankie567 ,
very good,
can you add please auth with google

**Comment by frankie567** [comment]
Yeah, good point, I'll do that!

**Comment by imkrish7** [comment]
hey @frankie567  whats the point setting /login content-type 'application/x-www-form-urlencoded' rather than 'application/json'
