### ISSUE TITLE
Use username instead of email ?

### ISSUE THREAD

**Issue by galvakojis** [frankie567/fastapi-users#168]
Quick question, can I change using a nick_name as a login name instead of email?
How to make email field optional, but not mandatory?

**Comment by frankie567** [comment]
Hi @galvakojis!

Well, this is one the first design choice I had to make when I started this library. Unfortunately, I think there is no easy way to do it "out-of-the-box".

A few directions however:

* I think you can overload the `User` Pydantic model to make the `email` field optional.
* You should overload the [`/register` route](https://github.com/frankie567/fastapi-users/blob/6292c15d77c5cd4fa5f0f120133b7b49db0f8f6b/fastapi_users/router/users.py#L94) to handle a username unicity check instead of email.
* You should overload the [`authenticate` method of the database adapter](https://github.com/frankie567/fastapi-users/blob/6292c15d77c5cd4fa5f0f120133b7b49db0f8f6b/fastapi_users/db/base.py#L45) to make it retrieve the user by username.

Hope it'll help!

**Comment by galvakojis** [comment]
already did the last of two and maybe first.

I think that only one problem left to solve[ is in this line ](https://github.com/frankie567/fastapi-users/blob/6292c15d77c5cd4fa5f0f120133b7b49db0f8f6b/fastapi_users/db/mongodb.py#L22)

But i don't know how to change (and when) email to` unique=False`

**Comment by frankie567** [comment]
If the email is not required, you can't have a `unique` index on this field, so you should remove this line. You should however  add a unique index on your username field.

**Comment by galvakojis** [comment]
UPDATE:

I added in my mongo-init.js (using Docker)
```
db.users.createIndex({ email: 1 }, { unique: false });
db.users.createIndex({ nick_name: 1 }, { unique: true });
```

so now I can have as many users without email as i want, but with different nick_name without changing core files.

**Comment by frankie567** [comment]
I assume your problem is solved, so I'll close this :)

**Comment by davidbrochart** [comment]
The [POST /login](https://fastapi-users.github.io/fastapi-users/11.0/usage/routes/#post-login) route needs a `username` and a `password`, but the `username` is actually the `email` given at [POST /register](https://fastapi-users.github.io/fastapi-users/11.0/usage/routes/#post-register), which also has a `username` that can be something else than an email.
This is a bit confusing, maybe the request body at `POST /login` should have an `email` instead of a `username`?
I have the feeling that we already discussed this issue, sorry if it's the case!

**Comment by frankie567** [comment]
@davidbrochart The problem here is that we use the built-in [OAuth2PasswordRequestForm](https://github.com/tiangolo/fastapi/blob/d6fb9429d21c6492b2541b7210ecc9707b8677e2/fastapi/security/oauth2.py#L13), which defined by FastAPI to generate the correct form in Swagger. If we don't use it, we lose the auth integration in Swagger.

**Comment by DoobyDouglas** [comment]
The best way is a make custom OAuth2PasswordRequestForm with email in __init__.

**Comment by jstpierre-sirix** [comment]
In case this can be of any help to others, I went for a different approach. I have overridden `get_by_email` behavior to support username instead. Unlike OP, I still needed the email column for other uses so I did not need to make it optional or anything.


```python
from fastapi import Depends
from fastapi_users import BaseUserManager, IntegerIDMixin, models, exceptions
from fastapi_users_db_sqlalchemy import SQLAlchemyUserDatabase

import sqlalchemy as sa
from sqlmodel import select

from app.models.user import User


class BaseUserManagerExtended(BaseUserManager[models.UP, models.ID]):
    async def get_by_email(self, user_email: str) -> models.UP:
        """
        Get a user by e-mail or username.
        """
        if "@" in user_email:
            return await super().get_by_email(user_email)
        else:
            result = await self.user_db.session.execute(select(User).where(sa.func.lower(User.username) == user_email.lower()))
            user = result.scalar_one_or_none()

            if user is None:
                raise exceptions.UserNotExists()

            return user

...

class UserManager(IntegerIDMixin, BaseUserManagerExtended[User, int]):
    ...

async def get_user_manager(user_db: SQLAlchemyUserDatabase = Depends(get_user_db)):
    yield UserManager(user_db)

...

```

Then to accept the username parameter, you simply need to update the models your passed in the `fastapi_users.get_*_routers(...)`
