### ISSUE TITLE
Swagger issue for endpoints register & update

### ISSUE THREAD

**Issue by anancarv** [frankie567/fastapi-users#171]
Hi, 
First of all, great job. It's a very useful library.

However, after having setup my project. I noticed a few issues in the generated Swagger documentation. Indeed, the request body is pre-filled with the following information:
```
{
  "id": "string",
  "email": "user@example.com",
  "is_active": true,
  "is_superuser": false,
  "password": "string"
}
```

However, according to your documentation, only the fields `email` & `password` are required. It can lead to some misunderstandings for someone wanting to use the API for the first time since the Swagger (or redoc) should describe how to use the API.

I think it's a cheap fix that can be very useful for when you'll find a solution for adding auth in the Swagger. Indeed, after having had a look at your code, one solution could be to make the models `BaseUserCreate` and `BaseUserUpdate` not to inherit from `BaseUser` but `BaseModel` instead.

Looking forward to hearing from you :)

**Comment by frankie567** [comment]
You're right, it's misleading! I'll look into it :)

**Comment by martincolladofab** [comment]
As @anancarv comments, looks like a inheritance problem, when the BaseUser is used instead of BaseModel.

**Comment by nullhack** [comment]
I took the weekend to play with fastapi-users. I noticed the full examples work fine from command line, but on swagger documentation, things just don't match as nice as the (much simpler) example on [fastapi documentation](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/).

I think most the issues are related to inheritance as @martincolladofab described. I solved the authorization [issue](https://github.com/frankie567/fastapi-users/issues/211) by just setting TokenUrl. But the issue described here and the fact that even after authorization the curl command generated has a `"Authorization: Bearer Undefined"`, I could not solve yet. (Anyone can give some guidance on this? I think I can fix, just need some guidance)

**Comment by martincolladofab** [comment]
@nullhack yesteday I was playing with your PR https://github.com/frankie567/fastapi-users/pull/210 and I noticed the problem with the `Authorization: Bearer Undefined`. Looks a problem with Swagger UI rather than fastapi-users, but just in case that could work. Did you tried to change the response from the access token from `token` to `access_token`? Probably Swagger UI is not taking the response data from just `token`
https://github.com/frankie567/fastapi-users/blob/52260f6a658524573fba8949cc2795b9f40db4b5/fastapi_users/authentication/jwt.py#L66-L68

(I didn't tried, and probably is not correct what I'm saying, it's just an idea)

**Comment by nullhack** [comment]
I'll take a look on the weekend. But I don't think is on Swagger UI because fastapi integrates well with the documentation, so the problem seems to be in between the integration fastapi-users and fastapi. I'm trying to understand better how the token is used on fastapi side and how it integrates with the documentation

**Comment by nullhack** [comment]
Thanks @martincolladofab That is the file I needed to change indeed. I could not wait until the weekend, so I solved It based on the base code for fastapi (PR https://github.com/frankie567/fastapi-users/pull/213 - I just saw that something on pytest broke, tomorrow I'll take a look).

Now the last challenge to completely integrate swagger is this issue. Probably will require changes on the base classes.

**Comment by frankie567** [comment]
Sorry I couldn't intervene this weekend, I really appreciate your help 😃

Maybe the key indeed is to not make `BaseUserCreate` inherit from `BaseUser`:

https://github.com/frankie567/fastapi-users/blob/e850871e7935c460e9c169385dd7d42b45e0320c/fastapi_users/models.py#L29-L31

The good thing is that it will allow end-developer to specify which field are required at registration, and the ones that are not.

**Comment by martincolladofab** [comment]
@frankie567 I have a PR to fix this issue. When I try to push to make a PR gives me an permissions problem. How could I make the PR?

**Comment by frankie567** [comment]
I suppose you didn't fork and try to push on the main repository 😄  You should read about forks and pull requests on GitHub, e.g https://guides.github.com/activities/forking/

It's easy and will make you a complete OSS contributor 😉

**Comment by martincolladofab** [comment]
Thanks @frankie567! I sent the PR :)

**Comment by silllli** [comment]
It seems that the problem with the generated documentation @anancarv mentioned was reintroduced along the way. 

`BaseUserCreate` is now defined as

```
class BaseUserCreate(CreateUpdateDictModel):
    email: EmailStr
    password: str
    is_active: Optional[bool] = True
    is_superuser: Optional[bool] = False
    is_verified: Optional[bool] = False
```

Or should I define my own `BaseUserCreate` model (inheriting from `CreateUpdateDictModel`) instead of using `fastapi-users`’, if it should only consist of `email` and `password`?
