### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by roshmath** [frankie567/fastapi-users#193]
Hi, love this project! Super cool and useful. I'm trying to implement it but having some issues using cookies. 

After logging in and being issued a cookie, every protected route returns a `401:  "detail": "Unauthorized"` 
I've checked and:

-  my only `auth_backends` is CookieAuthentication

- my SECRET variable is linked

- and cookies are attached to the headers of my responses in the browser. Currently, using [Insomnia REST](https://insomnia.rest/) to test my API which automatically attaches/manages cookies. 

Is there something else I could be missing?

**Comment by SelfhostedPro** [comment]
@roshmath can you say what the fix was?

**Comment by SelfhostedPro** [comment]
I believe the resolution may have been setting cookies_secure to False as that's what resolved it for me.

**Comment by frankie567** [comment]
Yes, you may have to set `cookie_secure` to `False` in local development to make it work. However, I **highly** recommend to make it an environment variable setting so that it's enabled in production. This way, the cookie is only sent over HTTPS connections.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
