### ISSUE TITLE
I can't inject get_current_active_users

### ISSUE THREAD

**Issue by renanaragao** [frankie567/fastapi-users#246]
How do I get an instance of fastapi_users in my file in a separate route file?

My folder structure:

app
   -  main.py (Where I instantiate fastapi_users)
   routers
     - users.py (where is my custom router)

**Comment by frankie567** [comment]
My advice would be to instantiate `fastapi_users` in its own file, so that you can import it in your main and your router files. Otherwise, you'll run into circular dependency issues. Something like:

* main.py
* dependencies
  * fastapi_users.py
* routers
  * users.py

You can then import it like `from dependencies.fastapi_users import fastapi_users`.

**Comment by renanaragao** [comment]
I'll try. Thank you

**Comment by renanaragao** [comment]
It worked really well. Thank you
