### ISSUE TITLE
CSRF cookies

### ISSUE THREAD

**Issue by SelfhostedPro** [frankie567/fastapi-users#291]
Hi, I think it would be beneficial to include csrf cookies along with the standard jwt cookies in order to help prevent your jwt tokens from getting stolen. 

You can see what flask-jwt-extended does here: https://github.com/vimalloc/flask-jwt-extended/blob/5bd8b1ed08ea64d23869a629af3c3c868816b8a8/flask_jwt_extended/utils.py#L260

**Comment by SelfhostedPro** [comment]
If you're able to, it may be beneficial to add documentation on manually adding a user via the Databases package in a similar way to how you do in the /register endpoint for people who would like to automatically generate an admin user if there currently are none.

**Comment by SelfhostedPro** [comment]
As far as the db stuff goes, this is what I have for creating a new user in a similar way to how the /register endpoint does. Please let me know if there's something wrong with doing things this way.

```py
from .auth import fastapi_users, get_auth_router, cookie_authentication, database, users, user_create, UserDB, get_password_hash #this is the file that fastapi-users is initialized in.

@app.on_event("startup")
async def startup():
    await database.connect()
    users_exist = await database.fetch_all(query=users.select())
    if users_exist:
        print("users exist")
    else:
        print("no users")
        hashed_password = get_password_hash(settings.ADMIN_PASSWORD)
        base_user = UserDB(
            id = uuid.uuid4(),
            email = settings.ADMIN_EMAIL,
            hashed_password = hashed_password,
            is_active = True,
            is_superuser = True
        )
        user_created = await user_create(base_user)
```

This is a function in the auth.py file that just exposes the same function that you use for the /register endpoint.
```py
async def user_create(UD):
    await fastapi_users.db.create(UD)
```

**Comment by frankie567** [comment]
Hi @SelfhostedPro!

I don't see anything wrong with the code you are showing ; even if I still personally think it's better to set the superuser flag manually from the database ; but that's okay!

As for the CSRF, I'll look further into it, thanks!

**Comment by frankie567** [comment]
I just discovered this project:  https://github.com/simonw/asgi-csrf

It's an ASGI middleware that handles CSRF protection. I'll look into this, but I think this would allow to implement this security without having to implement it in `fastapi-users`. If so, I'll add some documentation about how to setup it.

**Comment by SelfhostedPro** [comment]
Is there a way to disable the stale bot on a specific issue? That looks like it would work. It's unfortunate that they haven't responded to your issue though.

**Comment by frankie567** [comment]
Sorry! I didn't pay attention!

**Comment by Harrison88** [comment]
This got me interested in reading up on CSRF, and I thought it might be helpful to share what I learned as far as FastAPI-Users is concerned.

In short, it seems that FastAPI-Users is mostly secure against CSRF already.

Routes that are potential targets:
1. `/logout` -- but all the attacker would be able to do is cause your user to logout. Since logging out basically consists of deleting the session cookie, I'm not even sure if a browser would delete the cookie when the request originated in a different website.
2. `PATCH /me PATCH/DELETE /{user_id}` -- these would be my main concern. It could allow an attacker to update a user's password. Some barriers exist, though: the attacker wouldn't know the username, only the password that they set. So they would have to get a list of usernames and try the new password against all of them to find out which user's password they changed. Beyond that, I'm not sure that there's a way to do a CSRF attack on the PATCH method, [at least in modern browsers](https://owasp.org/www-community/attacks/csrf#other-http-methods). If you wanted to be sure, you could require the user to enter their password in order to update their account. The user update model would then have a "current_password" field, and that would be checked along with the session cookie.

Using CSRF Tokens would also protect these routes, but could be a bit tricky to implement. Unfortunately, the asgi-csrf middleware wouldn't work for this case. The problem is that you have to have a way of communicating the CSRF Token to the client that the attacker can't see, and then all forms/api clients will have to send the token. As mentioned, flask-jwt-extended accomplishes this by setting a cookie. The client would then have to read the cookie and submit the token in a separate header (that's what double submit means: the csrf token is sent back to the server both as a cookie, and manually in a custom header). Since a third-party attacker couldn't read the token in the cookie, only JS that came from the same origin would be able to submit the custom header.

The answer to this question goes over several ways that the CSRF Token can safely be communicated between the client and server, which I found helpful in understanding how it works: https://stackoverflow.com/questions/20504846/why-is-it-common-to-put-csrf-prevention-tokens-in-cookies

Here are the routes that are definitely already secure against CSRF.
Routes that don't require a session cookie to be sent:
1. `/login`
2. `/register`
3. `/forgot-password`
4. `/reset-password`
5. `/authorize`
6. `/callback`

Routes that don't change state on the server:
1. `GET /me`
2. `GET /{user_id}`
