### ISSUE TITLE
Protect /register ?

### ISSUE THREAD

**Issue by Atem18** [frankie567/fastapi-users#305]
Hi,

First, thanks for the plugin, it's really helpful.

Second, how can I protect the register route ? I would like to setup a super-admin user by default (like django, I will do it via CLI) and that after, only a logged-in super-admin can register people.

Thanks in advance for the answer.

**Comment by Atem18** [comment]
@frankie567 Any idea ?

**Comment by frankie567** [comment]
Hello!

It's actually pretty easy using the FastAPI ability to [add dependencies to a whole router](https://fastapi.tiangolo.com/tutorial/bigger-applications/#include-an-apirouter-with-a-prefix-tags-responses-and-dependencies). Since the `/register` router is available by itself in `fastapi-users`, you can do something like this:

```py
app.include_router(
    fastapi_users.get_register_router(on_after_register),
    prefix="/auth",
    tags=["auth"],
    dependencies=[Depends(fastapi_users.get_current_superuser)],
)
```

Cheers!

**Comment by Atem18** [comment]
@frankie567 Thanks, it works.
