### ISSUE TITLE
Get all users route

### ISSUE THREAD

**Issue by lockieRichter** [frankie567/fastapi-users#338]
Love the project and the ease that it can be implemented.

It would be great if there was an endpoint on the Users router that returned a list of the users. This would just return a list of the users that could be gotten from GET /{user_id} if you knew all the ID's.

**Comment by frankie567** [comment]
In the first versions, there used to be such endpoint. I removed it because it can vary greatly from one project to another : how you handle pagination ? Which users can call the endpoint? Which users can you see according to your permissions? And so on.

So I prefer the developers to implement it themselves so it perfectly fits their need 😃

**Comment by lefnire** [comment]
Definitely prefer individual devs to implement. I want control over

**Comment by lockieRichter** [comment]
That's a good point I hadn't considered.

I would have assumed that only admin users can call the endpoint and they can see all the users. But I think I agree that it's better to favour the flexibility of having developers implement it themselves with that all in mind.

Thanks for the response 👍
