### ISSUE TITLE
separate mongodb dependency for tests and packaged code

### ISSUE THREAD

**Issue by erkandem** [frankie567/fastapi-users#35]
Hey, 
first, thanks for sharing!

MongoDB is neat, but I don't use it and two issues arise from that:

 1.  this specific [test](https://github.com/frankie567/fastapi-users/blob/658161518a7bc2e27cedabfba7ed6bb678b5604c/tests/test_db_mongodb.py#L14
) fails - obviously - because I don't have MongoDB installed
 
 2. importing  `fastapi_user` after  `$ pip install fastapi-users[sqlalchemy]` fails (see stack trace below)

While the first issue is arguably a development issue the second seems to affect any user of the package.

### ideas for 1.
 - mock a MongoDB connection and don't connect to a real MongoDB database
 - add pytest configuration file to separate MongoDB related tests for human devs and CI

### ideas for 2.
my stack trace shows the missing `motor` package (MongoDB async driver). it works ok after installing `motor`  via `$ pip install motor`. But if this dependency is intended it should be listed in the pipenv file?
This happend although I used  `$ pip install fastapi-users[sqlalchemy]`. But I am not familiar with the underlying pip/PyPi/pipenv logic. Did the logic break?

```
/home/user/dev/py/fa/.venv2/bin/python /home/user/dev/py/fa/user/main.py
Traceback (most recent call last):
  File "/home/user/dev/py/fa/user/main.py", line 9, in <module>
    from src.db import db
  File "/home/user/dev/py/fa/user/src/db.py", line 3, in <module>
    from fastapi_users.fastapi_users.db import SQLAlchemyUserDatabase
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/__init__.py", line 5, in <module>
    from fastapi_users.fastapi_users import FastAPIUsers  # noqa: F401
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/fastapi_users.py", line 3, in <module>
    from fastapi_users.authentication import BaseAuthentication
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/authentication/__init__.py", line 1, in <module>
    from fastapi_users.authentication.base import BaseAuthentication  # noqa: F401
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/authentication/base.py", line 7, in <module>
    from fastapi_users.db import BaseUserDatabase
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/db/__init__.py", line 2, in <module>
    from fastapi_users.db.mongodb import MongoDBUserDatabase  # noqa: F401
  File "/home/user/dev/py/fa/.venv2/lib/python3.7/site-packages/fastapi_users/db/mongodb.py", line 3, in <module>
    from motor.motor_asyncio import AsyncIOMotorCollection
ModuleNotFoundError: No module named 'motor'

```

**Comment by frankie567** [comment]
Thank you for your feedback!

## Concerning 1.

Actually, there is a [`Makefile` with a `test` command](https://github.com/frankie567/fastapi-users/blob/658161518a7bc2e27cedabfba7ed6bb678b5604c/Makefile#L13-L16) that takes care of spawning a Docker MongoDB container. So if you have Docker installed, you should be able to run the tests with `make test`.

I'm aware that this may be a bit overkill, but I was reluctant to mock every `motor` calls ; sounds to me that there wasn't much value in the resulting tests.

To improve this, here is what I propose:

* Add a Development/Contributing section in the README to explain how to run the tests.
* Add pytest markers on the tests so that we can properly skip the ones we are not interested in.

Would that work for you?

## Concerning 2.

Well, I fear that I completely fucked up on this one. Indeed, when you are trying to import the SQLAlchemy class, the `db/__init__.py` file is loaded:

https://github.com/frankie567/fastapi-users/blob/658161518a7bc2e27cedabfba7ed6bb678b5604c/fastapi_users/db/__init__.py#L1-L6

It tries to load the MongoDB class, which refers to the `motor` library, which is not installed ; hence the error. This should be wrapped in `try/except` clauses. Really sorry for this! I'm fixing this right away.

**Comment by erkandem** [comment]
> Actually, there is a Makefile with a test command that takes care of spawning a Docker MongoDB container. So if you have Docker installed, you should be able to run the tests with make test.

to the fist one: I didn't touch the `Makefile` (It smelled like something for C-code). I don't know about the full spectrum of possible solutions, but I like the docker approach. I have postgres dependencies in own applications for which I can use this pattern.

to the second one:  glad this  is easy to fix

with regard to both issues: Thx :)

**Comment by frankie567** [comment]
Actually, you can use a `Makefile` to create some commands shortcuts, it's quite convenient. I've taken this idea from the [python package cookiecutter](https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile).

The release is underway for the import bug.

I'll create a separate ticker to track the documentation and tooling improvements regarding unit tests!
