### ISSUE TITLE
Token refresh

### ISSUE THREAD

**Issue by lvar** [frankie567/fastapi-users#350]
I have many doubts about token refresh implementation in the docs:

 

         from fastapi import Depends, Response

         @router.post("/auth/jwt/refresh")
         async def refresh_jwt(response: Response, user=Depends(fastapi_users.get_current_active_user)):
              return await jwt_authentication.get_login_response(user, response)

How can I use this function on a real project?...
About "get_current_active_user"  -> Will throw a 401 Unauthorized if missing or wrong credentials... by time I call this function the token already expired so the user is Unauthorized ...how could this work ?
What should I send in response param ?

**Comment by frankie567** [comment]
The purpose of this refresh endpoint is to get a new token while you still have a valid one.

A common use-case is to call it whenever your user gets back into your app. This way, you ensure you always have a fresh one before the previous expires.

You should call it with a JWT or Cookie (depending on what you use) ; like any other protected endpoint.

**Comment by lvar** [comment]
thank you!!

**Comment by izdwuut** [comment]
From what I see, you recommend to use existing token to refresh it. What if it leaks? The attacker could refresh it indefinitely and due to nature of JWT tokens, you'd be left with no option to revoke it. From what I know, it poses a security threat.

**Comment by frankie567** [comment]
This is exactly why it's not implemented by default in the library. Each developer has the liberty to implement it better.

**Comment by izdwuut** [comment]
I see. Well, thanks for clarifying that!

**Comment by lefnire** [comment]
I think a big draw to fastapi-users is how much it does for you. DB setup, routes, forgot-password, (verify email soon 🤞). I think refresh token is a requirement for most projects once they get off the ground, and it seems like a perfect fit to add to this library. For my part, I'm actually going to switch _off_ fastapi-users to fastapi-jwt-auth since it handles refresh tokens. I've wrestled some with how to use fastapi-users for 90%, and defer to fastapi-jwt-auth just for refresh tokens; but it seems it might turn into a Frankenstein, based on how they each handle jwt verification dependency-injection. Instead, I might switch it; use fastapi-jwt-auth as the core, and see about using fastapi-users just for forgot-password & other bits.

All that's to say: we definitely don't want to doubt your decision to defer refresh-tokens to the developer, you're close to the metal and know what's best. But you might find it's a deal-breaker for a lot of people (is for me), who don't know enough jwt/security to tackle this themselves, deferring instead to the experts (yourself). Unless there's some clear path to implementing proper refresh-token flow via fastapi-users on the developers' side that we're not seeing?

**Comment by frankie567** [comment]
Hey @lefnire!

Thank your for the detailed feedback! I totally get your point, and I think you convinced me 😅 I've checked `fastapi-jwt-auth` and their approach seems indeed interesting (I especially like the freshness pattern).

Now, as you surely know, open-source is *hard* and *time-consuming*. I would like to have more time to work on `fastapi-users`, but I'm quite busy at the moment.

But I promise you that I'll revisit (and also email verification 😉) this when I get time.

I see two ways of implementing this:

* Implement a logic similar to `fastapi-jwt-auth` in this library ;
* Implement an authentication class backed by `fastapi-jwt-auth`

I reopen this issue and mark it as enhancement. Thanks ;)

**Comment by lefnire** [comment]
That's wonderful news! Thanks for hearing us out.

> open-source is hard and time-consuming

No doubt, and thanks for all your work thus far. We were just concerned it was being marked "out of scope" rather than "help wanted / someday". Hopefully one of us can help!

**Comment by lefnire** [comment]
> Implement an authentication class backed by fastapi-jwt-auth

I think that (option 2) is a great idea personally, let them handle some of the guts and fastapi-users can be more the layer on top. Saves dev work, since contribs here can fix bugs there, instead of two places. Actually wonder if / how much of fastapi-users could be refactored to use fastapi-jwt-auth under the hood for current tasks, then you could focus more on the developer-facing features.

One trick worth consideration before work begins. Common practice that refresh tokens use `f"{SERVER_SECRET_KEY}{USER_PASSWORD}"` as the signing key for refresh tokens (not access tokens). Then what happens is refresh tokens on other devices are invalidated when a user changes their password. No password leakage here, since it's in the signing key (not the returned token). fastapi-jwt-auth doesn't have any example of that, since they're presenting as agnostic to use-case (eg, not just for user accounts).

**Comment by lefnire** [comment]
https://github.com/lefnire/gnothi/pull/124 if anyone wants to see how to blend fastapi-users + fastapi-jwt-auth to get refresh tokens

**Comment by lefnire** [comment]
The `{secret_key}{hashed_password}` approach via fastapi-jwt-auth might not be currently possible, ticket https://github.com/IndominusByte/fastapi-jwt-auth/issues/26. But he is considering the matter there.
