### ISSUE TITLE
Body content type for /login and /register

### ISSUE THREAD

**Issue by visini** [frankie567/fastapi-users#358]
Hi there!

I was looking into this project today. Why does `/login` require `Content-Type: application/x-www-form-urlencoded` (and not `Content-Type: application/json`), while `/register` requires `Content-Type: application/json`?

Is it due to being modelled after OAuth 2.0 specs? https://tools.ietf.org/html/rfc6749

However, some other routes require `Content-Type: application/x-www-form-urlencoded` as per the above document, while in `fastapi-users` the route `/login` is the only route with `Content-Type: application/x-www-form-urlencoded`.

Thanks for the clarification!

**Comment by frankie567** [comment]
Hi @visini!

Yes, it's due to the OAuth spec. Internally, `/login` uses the [builtin FastAPI `OAuth2PasswordRequestForm`](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#oauth2passwordrequestform) ; which works as a url-encoded form.

If that's bother you, you can easily implement a login endpoint that works with JSON, and take inspiration from the provided one.

**Comment by visini** [comment]
Thank you for clarifying!
