### ISSUE TITLE
Make easy to override Responses and HTTPException

### ISSUE THREAD

**Issue by prostomarkeloff** [frankie567/fastapi-users#44]
Hello! At the moment, i can't override values which returns fastapi-users. For example:
When user have bad credentials fastapi-user simple raise the FastAPI `HTTPException`, but in some cases it isn't well :( My idea is to make a classvars (or global vars?) of responses (errors) classes, which user easy can override.

**Comment by frankie567** [comment]
Hi! I don't really see the use case here. What type of responses would you like to return in those cases? Currently, they carefully follow REST best practices.

**Comment by prostomarkeloff** [comment]
Ok. For example i wanna return dict like {"response": {...}, "status": "ok"

**Comment by frankie567** [comment]
Well, I have to say I'm not a big fan of this style ; I truly think that relying on the HTTP status code is the way to go.

I don't really see an easy way to do this in the code base without adding lot of complexity.

I guess your best bet is to subclass the `UserRouter` in your project and include it instead of the default one in your routes.

**Comment by prostomarkeloff** [comment]
Ok, good solution.
